### ISSUE TITLE
[Bug]: Missing album art for tracks throughout UI

### ISSUE THREAD

**Issue by net-solution** [jeffvli/feishin#1449]
### I have already checked through the existing bug reports and found no duplicates

- [x] Yes

### App Version

1.0.1.beta.1.r44.gf78a572-1

### Music Server and Version

Gonic v0.16.4

### What happened?

Cover art for tracks is not being displayed throughout the application, such as in album or playlist listings, the player controls at the bottom, the right-hand queue panel, and the full-screen lyrics view.

Inspecting the DevTools, it appears this is technically the fault of the music server (Gonic), as for each of the missing cover artworks it receives XML data such as:
```xml
<subsonic-response status="failed" version="1.15.0" type="gonic" serverVersion="0.16.4" openSubsonic="true">
    <error code="10" message="couldn't find cover "tr-23850": could not find a cover with that id"/>
</subsonic-response>
```

This only occurs where the `getCoverArt` endpoint is given a track ID (e.g. `tr-23850`); when given an album ID (e.g. `al-5271`), artwork is found just fine.

<img width="1950" height="1346" alt="Image" src="https://github.com/user-attachments/assets/5e985a71-9c6d-4427-8531-537799247cfe" />

I am not sure if the issue thus lies with Gonic, the metadata of my tracks/albums, or if it would be within scope for Feishin to account for a situation like this (e.g., falling back to the track's album for artwork, instead of the track itself?).

I will attempt a PR to address this later today, though I would understand if you wanted this handled by yourself or not handled at all, if the changes spread too deeply and/or this is outside of Feishin's remit.

Otherwise, many thanks for this excellent application, it is a genuine joy to use.

### Steps to reproduce

1. Open Feishin, and connect to an OpenSubsonic server with no embedded artwork
  a. (In my case, I'm using Gonic and only have artwork stored as an image file in the album folder   
2. Play a track

The album art for the track should be displayed in the bottom left corner; no album art is displayed, nor any indication that the album art is missing (except for a blank space).

### Relevant log output

```shell

```

**Comment by jeffvli** [comment]
This *should* be resolved with my changes.

I think Gonic already adds a fallback to album image if not available, but I was using the wrong id to associate to the image fetch URL.

Let me know if it's fixed with the latest changes.

**Comment by net-solution** [comment]
Thank you very much, unfortunately the issue is still present after building from the latest commit: 

<img width="2843" height="1412" alt="Image" src="https://github.com/user-attachments/assets/b2c02dc0-d1c8-4b5d-944c-79aece2d69ff" />

I've cleared the Feishin caches as well just in case, but no change; Gonic returns the same "could not find a cover with that id" message for each track

**Comment by jeffvli** [comment]
Got it.

Feel free to submit a PR if you are able to resolve it.
I'm not sure there's a good way to handle this besides a setting that forces the controller to use the albumId over the existing coverArt id.

**Comment by jeffvli** [comment]
Ideally, gonic should return either null/undefined as the `coverArt` property if there's no available art, which would allow us to automatically fall back.

Does disabling the `GONIC_SCAN_EMBEDDED_COVER_ENABLED` config handle this?

**Comment by net-solution** [comment]
Thank you - for both the fixes and pointing me to `GONIC_SCAN_EMBEDDED_COVER_ENABLED`!  It took me longer than it should've to realise that the `gonic:latest` Docker image wasn't actually the latest, but `nightly` was. After updating Gonic, disabling that option, and rescanning the library, it now works perfectly.
