### ISSUE TITLE
No repeat still repeats the queue

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#55]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

I expected feishin to stop playing after the queue ended.

## Current Behavior

Feishin starts the playing again from the beginning of the queue.

## Steps to Reproduce

1. Make sure you're using the no repeat option.

2. Add a song or more to the queue .

3. Play and wait until the last song.

4. Feishin starts over.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by jeffvli** [comment]
Fixed for the next release.

**Comment by isle9** [comment]
This definitely still happens in 0.0.1-alpha6. Doesn't matter if it's one song or multiple.

**Comment by yacoob** [comment]
Still present in 0.3.0 :[
