### ISSUE TITLE
Keep getting logged out of Jellyfin-server

### ISSUE THREAD

**Issue by cyberwolfie1** [jeffvli/feishin#674]
### Expected Behavior

After entering login credentials in the server management tab, I should remain logged in for a while.

### Current Behavior

Very frequently, perhaps once every day, I am logged out of my Jellyfin server (running v. 10.9.7 on Docker) and I need to re-enter my password. A restart of the application is not sufficient to trigger this, so seems like some timeout issue or something. 

I am not entirely sure this is a Feishin issue, but I am not experiencing this issue in e.g. Finamp on Android that is logged into the same server. This started after I did an update from Jellyfin 10.8.x to 10.9.7, so I thought that there might have been some server side updates that has not been handled in Feishin yet that causes this? 

### Steps to Reproduce

1. Open Feishin 0.7.1 the day after last successful login to the Jellyfin (Docker-container running 10.9.7) server. 
2. Required to enter password again.

### Application version

0.7.1

### Operating System and version

Tuxedo OS 3 and Linux Mint 21.3

### Server and Version

Jellyfin 10.9.7

**Comment by jeffvli** [comment]
Fixed in #660 I believe. I haven't pushed the release with this fix yet.

**Comment by duckunix** [comment]
I know this is marked closed, but I am still seeing this on v0.12.3 of feishin and v0.55.1 of Navidrome.  I am running on NixOS if that helps.
